baseurl: https://atm-observatory.netlify.app/
title: Talent Management Observatory in Asian Universities
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: en
disqusShortname: vicencfernandez
googleAnalytics: 'G-V9BL7R4VZ7'
paginate: 10
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: blog
      name: News and Best Practices
      url: /blog/
      weight: 2
    - identifier: submit
      name: Submit your Best Practice
      url: /submit/
      weight: 3
    - identifier: toolkit
      name: ToolKit for TM Practices
      url: /toolkit/
      weight: 4        
  topbar:
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/vicencfernandez/atmObservatory
      weight: 1
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: https://twitter.com/TechTalentLab
      weight: 2
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:vicenc.fernandez@upc.edu
      weight: 3
params:
  about_us: <p>Talent Management Observatory of Asian Universities. Project co-founded by the Erasmus+ Programme of the European Union, and coordinated by the Universitat Politècnica de Catalunya.</p>
  address: "<p class=\"text-uppercase\"><strong>Universitat Politècnica de Catalunya · BarcelonaTech</strong>\n        <br>
  <br>TechTalent-Lab\n        <br>Jordi Girona 1-3, Building C5, Office 001\n        <br>08034 - Barcelona\n
    \       <br>\n        <strong>Spain</strong>\n      </p>\n      "
  author: Vicenc Fernandez
  carousel:
    enable: yes
  clients:
    enable: yes
    subtitle: 'Several Asian and European Universities have been working together to develop and maintain this online observatory of Talent Management Practices in the Asian Higher Education Instituions, as well as the Tool-Kit for designing Talent Management Practices'
    title: Our Partners
  contact_form_ajax: no
  copyright: Copyright (c) 2019 - 2021, Universitat Politècnica de Catalunya · BarcelonaTech; all rights reserved.
  date_format: January 2, 2006
  default_sharing_image: img/sharing-default.png
  defaultDescription: Site template made by devcows using hugo
  defaultKeywords:
    - devows
    - hugo
    - go
  enableGoogleMaps: no
  facebook_site: ''
  features:
    enable: yes
  formspree_action: https://formspree.io/sample/of/endpoint
  googleMapsApiKey: AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y
  latitude: '-12.043333'
  logo: img/logo.png
  logo_small: img/logo-small.png
  longitude: '-77.028333'
  mainSections: blog
  recent_posts:
    enable: yes
    subtitle: Here, you can find the last News and Talent Management Practices that have been published in this online observatory. We upload news and TM practices regularly with the objective of informing the community of the most recent contributions in the field.
    title: Last News and TM Practices
  see_more:
    enable: yes
    icon: far fa-file-alt
    link_text: Get the Physical Toolkit
    link_url: 'https://twitter.com/TechTalentLab'
    subtitle: We have designed and built a physical toolkit with the best materials and using the best quality processes to be used intensively by universities.
    title: Do you want to get the physical toolkit?
  style: blue
  testimonials:
    enable: yes
    subtitle: Professors, researchers, non-academic staff, and designers have participated in developing this toolkit. Here, some of their thoughts.  
    title: Collaborators
  topbar:
    enable: yes
    text: "<p class=\"hidden-sm hidden-xs\">Talent Management Observatory in Asian Universities</p>\n
      \     <p class=\"hidden-md hidden-lg\">Talent Management Observatory in Asian Universities</p>\n      "
  twitter_site: GoHugoIO
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:filename/
